[package]
name = "fireflow-python-proc"
version.workspace = true
edition.workspace = true

[dependencies]
syn = { version = "*", features = ["extra-traits"] }
itertools = { workspace = true }
quote = "*"
proc-macro2 = "*"

[lib]
proc-macro = true
