[package]
name = "pyreflow"
version = { workspace = true }
edition = { workspace = true }

[lib]
name = "pyreflow"
crate-type = ["cdylib"]

[dependencies]
fireflow-core = { version = "0.1.0", path = "../crates/fireflow-core" }
pyo3 = { version = "0.23.5", features = ["extension-module", "multiple-pymethods", "chrono"] }
num-traits = { workspace = true }
chrono = { workspace = true }
polars = { version = "0.46.0" }
pyo3-polars = { version = "0.20.0" }
polars-arrow = { version = "0.46.0" }
itertools = { workspace = true }
nalgebra = { workspace = true }
numpy = { version = "0.23", features = ["nalgebra"] }
nonempty = { workspace = true }